# Generated by Django 3.2.2 on 2021-10-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfname', models.CharField(max_length=20)),
                ('clname', models.CharField(max_length=20)),
                ('ccity', models.CharField(max_length=100)),
                ('crating', models.SmallIntegerField()),
                ('creview', models.TextField()),
            ],
        ),
    ]
