# Generated by Django 3.2.2 on 2021-10-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=100, verbose_name='Title')),
                ('service_about', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
