# Generated by Django 3.2.2 on 2021-10-22 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('betterclean', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdata',
            options={'verbose_name': 'Query', 'verbose_name_plural': 'Customer queries'},
        ),
        migrations.AddField(
            model_name='formdata',
            name='remark',
            field=models.TextField(blank=True, verbose_name='Remark'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='message',
            field=models.TextField(verbose_name='Query'),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Phone'),
        ),
    ]
